version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TABLE}
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - db
    volumes:
      - public:/app/ui/public:rw
  ui:
    build:
      context: ./
      dockerfile: ./ui/Dockerfile
    ports:
      - "${UI_PORT}:4173"
    volumes:
      - public:/app/ui/dist/public:ro

volumes:
  public:
