[tool.poetry]
name = "fomina-pw"
version = "0.1.0"
description = ""
authors = ["VodoGamer <vodogamer@yandex.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.100.0"


[tool.poetry.group.dev.dependencies]
uvicorn = "^0.23.0"
black = "^23.7.0"
ruff = "^0.0.278"

[tool.black]
line-length = 99
target-version = ['py310']

[tool.ruff]
select = ["I", "E", "F", "B", "Q"]
exclude = ["alembic"]
line-length = 99
target-version = "py310"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
