name: Backend CI

on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        id: python-setup
        with:
          python-version: "3.12"

      - uses: yezz123/setup-uv@v4

      - name: Select venv
        run: uv venv

      - name: Install dependencies
        run: uv pip install -r requirements-dev.lock

      - name: Activate venv
        run: |
          source .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Check code formatting
        run: ruff format .

      - name: Check code lint
        run: ruff check .

      - name: Check types by pyright
        run: pyright src
