name: Backend CI

on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v4

      - name: Install Rye
        id: setup-rye
        uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
          working-directory: api

      - uses: actions/setup-python@v4
        id: python-setup
        with:
          python-version: "3.12.2"

      - name: Install dependencies
        if: steps.setup-rye.outputs.cache-hit != 'true'
        run: rye config --set-bool behaivor.use-uv=true && rye sync --no-lock

      - name: Check code formatting
        run: rye fmt

      - name: Check code lint
        run: rye lint

      - name: Check types by pyright
        run: rye run pyright src
